### ISSUE TITLE
feature request: social volume type = ALL

### ISSUE THREAD

**Issue by josefansinger** [santiment/san-sdk#14]
The `Social Volume` metric in `Sanbase` is extremely helpful. But the API provides only four distinct `SocialVolumeType`. Not the social volume reported in Sanbase. One has to add three of these types in a second step.

Can you please add a `SocialVolumeType: ALL` which returns the social volume reported by Sanbase? Thanks.

```
{
  socialVolume(
    slug: "ethereum"
    from: "2019-12-01T00:00:00Z"
    to: "2019-12-31T00:00:00Z"
    interval: "1d"
    SocialVolumeType: ALL) {
      datetime
      mentionsCount
  }
}
```

**Comment by IvanIvanoff** [comment]
We have such flag for social dominance and the gainers/losers api -it's called `ALL` there, so I suggest we use the same name here

**Comment by josefansinger** [comment]
Yep, `ALL` is fine. As long as it will be easier to reproduce the Sanbase data with the API.

**Comment by IvanIvanoff** [comment]
Update (for all social issues): Not forgotten, still in progress, as we're rewriting the internal services computing the social data which takes more time

**Comment by IvanIvanoff** [comment]
@josefansinger All social metrics are now available via the getMetric API. Now you can use `social_volume_total` for projects or random words. For projects, you use the slug selector (check example) and for words, you use the `text` selector. The difference is that projects fallback to a more complex query than just the provided word. For example, in the case of `santiment` it would search for `santiment`, `san` but will exclude commonly seen combinations like `San Diego`, `San Francisco`, etc.

Project example: https://tinyurl.com/v3b2l82
Random word example: https://tinyurl.com/rd57wvr
The `text` field contains any Lucene query actually, so you can use `OR`, `AND`, `NOT` (or some more complex combinators): https://tinyurl.com/s98fgao

The previously existing `social_volume` has been split into two different metrics:
- social_volume - count number of mentions across the whole source
- community_messages_count - count the total number of messages in a given project dedicated server - used to measure how active is `sentiment's telegram server for example.AS

(The old sources ending with `CHATS_OVERVIEW` are of the first kind, `DISCUSSION_OVERVIEW` - of the second)
