### ISSUE TITLE
availableQueries incomplete

### ISSUE THREAD

**Issue by josefansinger** [santiment/san-sdk#19]
For example, [`dailyActiveDeposits(slug:"maker")`](https://api.santiment.net/graphiql?query=%7B%0A%20%20dailyActiveDeposits(slug%3A%22maker%22%2C%20from%3A%222019-11-21T00%3A00%3A00Z%22%2C%20to%3A%222020-02-17T00%3A00%3A00Z%22%2C%20interval%3A%221d%22)%20%7B%0A%20%20%20%20datetime%0A%20%20%20%20activeDeposits%0A%20%20%7D%0A%7D) works fine, but the query is not listed [here](https://api.santiment.net/graphiql?query=%7B%0A%20%20projectBySlug(slug%3A%20%22maker%22)%7B%20availableQueries%20%7D%0A%7D%0A).

**Comment by IvanIvanoff** [comment]
Hi, that was fast :smiley:

The deposits were updated to include other data than just `ethereum` less than 24 hours ago [here](https://github.com/santiment/sanbase2/pull/1782). With this PR the metric is added to the `getMetric` API as well.

When our frontend migrates to using the `getMetric` I'll add a deprecation warning to the active deposits query. This will be done to discourage using the old `dailyActiveDeposits` query in favour of `get_metric(metric: "active_deposits")`. A few reasons to migrate to `getMetric` are:
- Unified way to access metrics - you don't need to know the fields name, query name and query arguments;
- The `getMetric` exposes additional metadata, the availableSince field and the lastDatetimeComputedAt field;
- The `getMetric` API is newer, better internally designed and thus much easier to maintain and extend.

With these things said you should consider using [this query](https://api.santiment.net/graphiql?query=%7B%0A%20%20getMetric(metric%3A%20%22active_deposits%22)%20%7B%0A%20%20%20%20timeseriesData(slug%3A%20%22santiment%22%2C%20from%3A%20%222017-12-01T00%3A00%3A00%2B00%3A00%22%2C%20to%3A%20%222018-01-01T21%3A00%3A00%2B00%3A00%22%2C%20interval%3A%20%227d%22%2C%20aggregation%3AMAX)%20%7B%0A%20%20%20%20%20%20datetime%0A%20%20%20%20%20%20value%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D%0A&variables=%7B%7D)

Example for a deprecated query in favor of getMetric:
![image](https://user-images.githubusercontent.com/6518376/74828677-32832f00-5318-11ea-8901-c0d167b6e820.png)

**Comment by josefansinger** [comment]
@IvanIvanoff `getMetric()` is much more elegant. Appreciate your continued improvements of the API.
