### ISSUE TITLE
volume for ERC20 / ETH pairs

### ISSUE THREAD

**Issue by josefansinger** [santiment/san-sdk#22]
The API allows to query prices in `USD` and `BTC`, see `price_usd` and `price_btc`.

For many ERC20 tokens `price_eth` is of interest which can easily be constructed.
For example, `ZRX/ETH = (ZRX/USD) / (ETH/USD)`.

But how can I retrieve `volume_eth` for the `ZRX/ETH` pair?

**Comment by IvanIvanoff** [comment]
There is no out-of-the-box ETH volume stored in our databses.

`volume_eth` would be constructed as `volume_usd(slug: "0x")` / `price_usd(slug: "ethereum")` (both timeseries data, division is for the points with same datetimes).

For example, if the last USD volume for 0x at 2020-01-01 is $10,935,427 and the average ETH price for the same day is $131, then the volume in ETH is 10,935,427 / 131 = 83,477 ETH

Note: The volume_usd for every datetime is actually the volume for the past 24h at this point, so you *cannot* `SUM` the volume (as you would have many overlapped windows). If you take the `LAST` volume_usd at a given day, you're getting the last volume on that day (~23:59:59) which shows the volume for the past 24h, so you essentially get the volume for that day.

**Comment by josefansinger** [comment]
Thanks. The last comment was important!

But `volume ZRX/ETH` is not `volume ZRX/USD` / `price ETH/USD`. The volume of the two trading pairs `ZRX/ETH` and `ZRX/USD` say on Kraken are entirely independent. But your suggestion is the next best approximation.

If the exchanges do not report separate volumes, let's close the issue.
But it would be nice to have.

**Comment by IvanIvanoff** [comment]
The USD volume we have is including all trading pairs, for example 0x includes (and ~160 more pairs from different exchanges)
![image](https://user-images.githubusercontent.com/6518376/75252836-1d117780-57e6-11ea-9534-f8820a5ca2b1.png)

Currently, there's no API to fetch the volume of a given trading pair on a given exchange.

Although for some time we've been getting raw data from a few exchanges:
Example of the raw data:
![image](https://user-images.githubusercontent.com/6518376/75253186-b8a2e800-57e6-11ea-81fe-bc5d50dab818.png)

- Binance 
- Bitfinex 
- Bittrex 
- Kraken   
- Poloniex 

This data is only exposed as a subscription now (we push you new data when it arrives), no way to query historical data.

On top of this data, I believe we can build what you need. 
A few questions now:
1. What exactly would you like to see built on top of this data?
2. What other exchanges do you think we should add?
3. Are you more interested in historical or realtime data? (Historical data is hard/expensive to find.)

PS: We also have the exchange market depth for the same exchanges/time period.

**Comment by josefansinger** [comment]
@IvanIvanoff For me these volumes have low priority.

But historic data would be interesting (and as you say expensive). The information would allow us to reconstruct the flow of value among chains, say between `USDT/BTC`, `USDT/ETH` and `ETH/BTC`. The changing market caps would be a good cross-check.
