### ISSUE TITLE
social_volume_total returns incorrect time frame

### ISSUE THREAD

**Issue by josefansinger** [santiment/san-sdk#24]
I have tested the new `social_volume_total` metric for `ethereum` for the time frame `2015-08-07` to `2020-03-06`. The results cover only `2016-06-10` to `2018-07-06`, although I have Pro access rights. See discussion [here](https://github.com/santiment/san-sdk/issues/23#issuecomment-595772573). The metric is missing for dates in 2015, 2019 and 2020.

As a second point, queries should always return all data points of the time frame `(from, to)`. If the metric is not available, `NA` values should be returned. See discussion [here](https://github.com/santiment/san-sdk/issues/23#issuecomment-595758682).

**Comment by IvanIvanoff** [comment]
Work is in progress, can't link to it as it's in private repositories.

**Comment by IvanIvanoff** [comment]
The `*_total*` social queries have been fixed to properly combine the data from different sources (so the data is not cut off before 2016-06-10 and after 2018-07-06 in the reported [case](https://api.santiment.net/graphiql?variables=%7B%7D&query=%7B%0A%20%20getMetric(metric%3A%20%22social_volume_total%22)%20%7B%0A%20%20%20%20timeseriesData(slug%3A%22ethereum%22%2C%20includeIncompleteData%3A%20true%2C%20from%3A%20%222015-03-10T00%3A00%3A00Z%22%2C%20to%3A%222020-03-14T00%3A00%3A00Z%22%2C%20interval%3A%20%221d%22)%20%7B%0A%20%20%20%20%20%20datetime%0A%20%20%20%20%20%20value%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D)). Currently the total combines data from 4 sources, earliest of which is `reddit` starting on 2016-01-01.

`availableSince` wrongly reports `2009-11-22` because since then we have some bitcointalk data but it's not included in the `*_total` metrics.

**Comment by josefansinger** [comment]
@IvanIvanoff Thank you. Great that you now report a value for every date of the time period.

But for bitcoin the earliest date I get is 20/12/2019 with Pro account. Even on Sanbase I get earlier dates. Please see also Sanbase crash for `social volume`, `bitcoin` and `time period = all`.

<img width="1170" alt="Screenshot 2020-03-18 at 10 39 15" src="https://user-images.githubusercontent.com/59919615/76946983-39946180-6905-11ea-9838-b4615472295d.png">

**Comment by IvanIvanoff** [comment]
> But for bitcoin the earliest date I get is 20/12/2019 with Pro account
How do you query the data?
![image](https://user-images.githubusercontent.com/6518376/76966384-8e000700-692e-11ea-9be8-76edd453e179.png)

**Comment by josefansinger** [comment]
[Here](https://api.santiment.net/graphiql?query=%7B%0A%20%20getMetric(metric%3A%22social_volume_total%22)%20%7B%0A%20%20%20%20timeseriesData(%0A%20%20%20%20%20%20slug%3A%20%22ethereum%22%0A%20%20%20%20%20%20from%3A%20%222015-01-01T00%3A00%3A00Z%22%0A%20%20%20%20%20%20to%3A%20%222020-03-03T00%3A00%3A00Z%22%0A%20%20%20%20%20%20interval%3A%221d%22)%20%7B%0A%20%20%20%20%20%20%20%20datetime%0A%20%20%20%20%20%20%20%20value%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%20%20%7D) again missing dates. Anything incorrect in my query?

<img width="1095" alt="Screenshot 2020-03-18 at 14 45 34" src="https://user-images.githubusercontent.com/59919615/76967072-2c886a00-6927-11ea-8d8d-1b26ca8ced6e.png">

**Comment by josefansinger** [comment]
@IvanIvanoff I cannot reproduce the [query](https://api.santiment.net/graphiql?query=%7B%0A%20%20getMetric(metric%3A%22social_volume_total%22)%20%7B%0A%20%20%20%20timeseriesData(%0A%20%20%20%20%20%20slug%3A%20%22bitcoin%22%0A%20%20%20%20%20%20from%3A%20%222015-02-18T00%3A00%3A00Z%22%0A%20%20%20%20%20%20to%3A%20%222020-03-19T00%3A00%3A00Z%22%0A%20%20%20%20%20%20interval%3A%2230d%22)%20%7B%0A%20%20%20%20%20%20%20%20datetime%0A%20%20%20%20%20%20%20%20value%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%20%20%7D
) from your screenshot.

<img width="1089" alt="Screenshot 2020-03-18 at 14 52 32" src="https://user-images.githubusercontent.com/59919615/76967861-40809b80-6928-11ea-916f-7fbe85e24c7f.png">

**Comment by IvanIvanoff** [comment]
What is the result that you get? Are you logged into sanbase from the same browser you execute the query?
You can check here what are the subscriptions currently used and what are the restrictions applied to different queries/metrics: [here](https://api.santiment.net/graphiql?query=%7B%0A%20%20currentUser%20%7B%0A%20%20%20%20subscriptions%20%7B%0A%20%20%20%20%20%20status%0A%20%20%20%20%20%20plan%20%7B%0A%20%20%20%20%20%20%20%20name%0A%20%20%20%20%20%20%20%20product%20%7B%0A%20%20%20%20%20%20%20%20%20%20name%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%20%20%7D%0A%20%20getAccessRestrictions%20%7B%0A%20%20%20%20name%0A%20%20%20%20isRestricted%0A%20%20%20%20restrictedFrom%0A%20%20%20%20restrictedTo%0A%20%20%7D%0A%7D%0A)

For example I see:
```json
     {
        "isRestricted": true,
        "name": "social_volume_total",
        "restrictedFrom": "2015-03-20T15:12:05Z",
        "restrictedTo": "2020-03-18T15:12:05Z"
      }
```

**Comment by josefansinger** [comment]
Yep, correct. Seems my trial period did run out.
```
{
        "isRestricted": true,
        "name": "social_volume_total",
        "restrictedFrom": "2018-03-19T15:23:05Z",
        "restrictedTo": "2020-02-17T15:23:05Z"
 }
```
@balresch Can you please extend my pro account? Then I will continue testing. Thanks.

**Comment by josefansinger** [comment]
Max extended my trial access. Thanks.
Let me do some further testing. I will then close the issue.

**Comment by josefansinger** [comment]
@balresch I checked `getAccessRestrictions()` with [`GraphiQL`](https://api.santiment.net/graphiql?query=%7B%0A%20%20getAccessRestrictions%20%7B%0A%20%20%20%20name%0A%20%20%20%20isRestricted%0A%20%20%20%20restrictedFrom%0A%20%20%20%20restrictedTo%0A%20%20%7D%0A%7D%0A) and with `ghql` in `R`, see code below. They are not identical. Is my email address (for `GraphiQL`) linked to my API key (for `ghql` in `R`)?
```
library(ghql)

# Santiment URL and API key
SANTIMENT_API_URL <- "https://api.santiment.net/graphql"
SANTIMENT_API_KEY <- "y4i...2xa"

 # new client
 client <- GraphqlClient$new(
   url = SANTIMENT_API_URL,
   headers = add_headers(Authorization = paste0("Apikey ", SANTIMENT_API_KEY))
 )

 # get access restrictions
 query <- Query$new()
 query$query('sanmetric', '{
   getAccessRestrictions {
     name
     isRestricted
     restrictedFrom
     restrictedTo
   }
 }')
```

**Comment by IvanIvanoff** [comment]
They are not identical because in graphiql the backend recognizes this as coming from a browser and applies Sanbase restrictions while in R it uses an API key and applies API restrictions

**Comment by josefansinger** [comment]
Yesterday, @balresch did lift my Sanbase restrictions but not my API restrictions. Could you please give me API access as well (`y4i...2xa`)?

**Comment by balresch** [comment]
Hey @josefansinger ,
I gave you trial access for API yesterday, not for Sanbase. So from how I understand Ivan, you should see full data when using R while being restricted when making that request through a browser.

**Comment by josefansinger** [comment]
In Sanbase I have access from `2016-01-01` (not from `2015-03-21` as stated below).
```
{
        "isRestricted": true,
        "name": "social_volume_total",
        "restrictedFrom": "2015-03-21T08:22:21Z",
        "restrictedTo": "2020-03-19T08:22:21Z"
}
```
In SanAPI I also have access from  `2016-01-01` (but this morning it was 2018).
```
{
        "isRestricted": false,
        "name": "social_volume_total",
        "restrictedFrom": null,
        "restrictedTo": null
}
```
So `getAccessRestrictions()` is not linked as @IvanIvanoff said. But it would be easier for me if it was consistent. In both cases I would expect to see data from at least as early as `2015-03-21`.

**Comment by IvanIvanoff** [comment]
> getAccessRestrictions() is not linked as @IvanIvanoff said

What do you mean by that? 

Note that restriction is not equal to available data. Restrictions are showing you that a metric can be fetched from this datetime onwards. Restrictions are calculated as `time now minus the days specified in the subscription plan`. For example `dailyActiveAddresses` returns data not since `restrictedFrom` but since the contract was created on the chain. If the contract is older than the restriction, then some data won't be available to you. But if the contract is newer, the first datetime returned could be years after `restrictedFrom`

As described above (or in another issue), social data is not so well suited for defining `availableFrom` like on-chain data because of its nature, so some inconsistencies can be seen here and there.

**Comment by josefansinger** [comment]
If I make any query (for example `getAccessRestrictions`) I would expect to get identical results in `GraphiQL` (where I identify myself by email) and in `R` (where I identify myself by API key which I got through my email). That is not the case, see [here](https://github.com/santiment/san-sdk/issues/24#issuecomment-601118791).

**Comment by josefansinger** [comment]
[Yesterday](https://github.com/santiment/san-sdk/issues/24#issuecomment-600520871) I tested `social_volume_total` . The query returned a date-value-pair for every date in of the time period `(from, to)`. Zero values were returned for dates which were not available or restricted. (Though I would have preferred `NA`.)

Now that is no longer the case. You do this for [`dev_activity`](https://api.santiment.net/graphiql?query=%7B%0A%20%20getMetric(metric%3A%22dev_activity%22)%20%7B%0A%20%20%20%20timeseriesData(%0A%20%20%20%20%20%20slug%3A%20%22ethereum%22%0A%20%20%20%20%20%20from%3A%20%222013-08-07T00%3A00%3A00Z%22%0A%20%20%20%20%20%20to%3A%20%222020-03-18T00%3A00%3A00Z%22%0A%20%20%20%20%20%20interval%3A%221d%22)%20%7B%0A%20%20%20%20%20%20%20%20datetime%0A%20%20%20%20%20%20%20%20value%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%7D) (2013 values are zero) but you do not for [`social_volume_total`](https://api.santiment.net/graphiql?query=%7B%0A%20%20getMetric(metric%3A%22social_volume_total%22)%20%7B%0A%20%20%20%20timeseriesData(%0A%20%20%20%20%20%20slug%3A%20%22ethereum%22%0A%20%20%20%20%20%20from%3A%20%222013-08-07T00%3A00%3A00Z%22%0A%20%20%20%20%20%20to%3A%20%222020-03-18T00%3A00%3A00Z%22%0A%20%20%20%20%20%20interval%3A%221d%22)%20%7B%0A%20%20%20%20%20%20%20%20datetime%0A%20%20%20%20%20%20%20%20value%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%7D) (no 2013 values reported). Consistent behaviour would make it easier for downstream development.

**Comment by IvanIvanoff** [comment]
The zero filling is still in progress by @ipranovich as written here: https://github.com/santiment/san-sdk/issues/23#issuecomment-595758682

The issue is that the data is fetched from 3-4 different databases, some of them make gap filling easy, some of them - not

**Comment by josefansinger** [comment]
@IvanIvanoff Ok, thanks. I will wait and not fill the gaps from my side. :+1:

**Comment by IvanIvanoff** [comment]
By the way, social metrics (volume, dominance, etc.) should be the only ones with such behavior now. If something else behaves this way it should be considered and reported as a bug.

An exception is the price/volume/marketcap data - if our 3rd party provider has gaps there is no valid value that can be filled - zeroes are not ok, filling with last seen value is kind of ok, but this way a spike/dip is removed, which could be valuable information.

**Comment by josefansinger** [comment]
Ok. Thanks. @IvanIvanoff 

Do you understand the [Sanbase/SanAPI inconsistency](https://github.com/santiment/san-sdk/issues/24#issuecomment-601131225)? Does that answer your question?

**Comment by IvanIvanoff** [comment]
Yes, the reason is: https://github.com/santiment/san-sdk/issues/24#issuecomment-601052473
sanbase and api restrictions are different (different historical and realtime restrictions) https://academy.santiment.net/products-and-plans/access-plans/

**Comment by josefansinger** [comment]
Ok. That part is closed then. 😄

**Comment by lars20070** [comment]
@IvanIvanoff @balresch New problem with `social_volume_total`. Most recent data are missing. For example, for `bitcoin` and `ethereum` since 2017 and 2019 respectively. See plots below. My access rights are ok. `getAccessRestrictions` --> `isRestricted = FALSE`
![SocialVolume_all_btc_usd](https://user-images.githubusercontent.com/6149805/77624706-84842980-6f42-11ea-8d89-f126fac61a3b.png)
![SocialVolume_all_eth_usd](https://user-images.githubusercontent.com/6149805/77624712-864ded00-6f42-11ea-8ead-c217df2f6506.png)

**Comment by josefansinger** [comment]
@IvanIvanoff @balresch New problem with `social_volume_total` since **yesterday evening**. The most recent data are missing. For example for `bitcoin` and `ethereum` since 2017 and 2019 respectively. My access rights are ok. `getAccessRestrictions` --> `isRestricted = FALSE`
![SocialVolume_all_btc_usd](https://user-images.githubusercontent.com/59919615/77625050-273ca800-6f43-11ea-8555-e7e9d11f4cc7.png)
![SocialVolume_all_eth_usd](https://user-images.githubusercontent.com/59919615/77625053-286dd500-6f43-11ea-964c-a0b76fa63796.png)

**Comment by valo** [comment]
Interesting. Seems like using a long time frame yield zeros for the end of the period:
https://api.santiment.net/graphiql?query=%7B%0A%20%20getMetric(metric%3A%22social_volume_total%22)%20%7B%0A%20%20%20%20timeseriesData(%0A%20%20%20%20%20%20slug%3A%20%22bitcoin%22%0A%20%20%20%20%20%20from%3A%20%222013-08-07T00%3A00%3A00Z%22%0A%20%20%20%20%20%20to%3A%20%222020-03-18T00%3A00%3A00Z%22%0A%20%20%20%20%20%20interval%3A%221d%22)%20%7B%0A%20%20%20%20%20%20%20%20datetime%0A%20%20%20%20%20%20%20%20value%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%7D

But if the time interval is reduced, the data is ok: https://api.santiment.net/graphiql?query=%7B%0A%20%20getMetric(metric%3A%22social_volume_total%22)%20%7B%0A%20%20%20%20timeseriesData(%0A%20%20%20%20%20%20slug%3A%20%22bitcoin%22%0A%20%20%20%20%20%20from%3A%20%222018-08-07T00%3A00%3A00Z%22%0A%20%20%20%20%20%20to%3A%20%222020-03-18T00%3A00%3A00Z%22%0A%20%20%20%20%20%20interval%3A%221d%22)%20%7B%0A%20%20%20%20%20%20%20%20datetime%0A%20%20%20%20%20%20%20%20value%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%7D

Looks like we are hitting some kind of limit/throttling in the API.

**Comment by josefansinger** [comment]
FYI. Maybe `dev_activity` [related](https://github.com/santiment/san-sdk/issues/17#issuecomment-601250150).

**Comment by josefansinger** [comment]
Also problems with `top-100-holders` in `ethereum`. 😕
`top-10-holders` is fine.
Not sure if you want to discuss this in separate issues.
![TopHolders_all_eth_usd](https://user-images.githubusercontent.com/59919615/77632664-9bc91400-6f4e-11ea-9aea-802c97cee13c.png)

**Comment by IvanIvanoff** [comment]
@ipranovich Seems like an issue with the latest social volume updates yesterday, please check ☝️

**Comment by josefansinger** [comment]
Are you currently load testing the API? I haven't looked into this much. But maybe a combination of Travis Continuous Integration and [EasyGraphQL](https://github.com/EasyGraphQL) can be a good testing framework. Better than us sending failing examples back and forth.

**Comment by IvanIvanoff** [comment]
The timeframe issue has been "fixed" by reverting the zero-filling changes. We'll try another approach soon.

---

We're running some performance tests, but not much - https://github.com/santiment/performance_tests. We also use have an in-house API call data analysis tool that allows us to follow API calls and their durations nicely. 

The main "issue" with running a load test is that you get very different results whether you hit the cache or the metric/from/to/interval params you use are not cached and a DB call is made. 

Currently, the spikes to our API are around 30 req/sec which is handled with no issues. The performance tests show consistently that 100 req/sec is reached with the current infrastructure (we're not running the API server on big machines, just 1 CPU and a few gigs of RAM).

Locally  (MacBook Pro,  i7-8559U, 16GB RAM) when benchmarking the cache, a single API server instance was able to serve 2k req/sec purely from the cache (so no internet bandwidth or database query execution speed is playing a part here), 

---

I am closing this issue as here we've been discussing a lot of off-topic and not related to the original issue.

**Comment by josefansinger** [comment]
Ok, good point.

Currently, I still have three open issues.
(1) [`social_volume_total`](https://github.com/santiment/san-sdk/issues/24#issuecomment-604293321) (ethereum and bitcoin)
(2) [`dev_activity`](https://github.com/santiment/san-sdk/issues/17#issuecomment-601250150) (ethereum)
(3) [`top_100_holders`](https://github.com/santiment/san-sdk/issues/24#issuecomment-604329721) (ethereum)

@IvanIvanoff Three separate issues?

**Comment by lars20070** [comment]
FYI, both (2) and (3) are now resolved. What remains is (1) i.e. #17.

**Comment by josefansinger** [comment]
FYI, both (2) and (3) are now resolved. What remains is (1) i.e. #17.
